#pragma config(Sensor, in4,    POT,            sensorPotentiometer)
#pragma config(Sensor, in6,    light_sensor,   sensorReflection)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Use your active directionality sensing device from Part 2 to allow Squarebot to find and approach a light source.
//You may find it necessary to periodically rescan for the light direction, although it is also possible to make
//continuous corrections as your robot drives toward the light source. If it cannot find the light source, it should
//wander randomly until the light comes into view.



	//int sensor_value;
	//sensor_value = SensorValue(POT);

//Functions for different turns

void moveHardLeft(){
	motor[leftMotor] = -40;
	motor[rightMotor] = 40;
	wait1Msec(700);
	motor[leftMotor] = 40;
	motor[rightMotor] = 40;
	wait1Msec(2000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
void moveSoftLeft(){
	motor[leftMotor] = 20;
	motor[rightMotor] = 80;
	wait1Msec(300);
	motor[leftMotor] = 40;
	motor[rightMotor] = 40;
	wait1Msec(2000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
void moveStraight(){
	motor[leftMotor] = 50;
	motor[rightMotor] = 38;
	wait1Msec(4000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
void moveSoftRight(){
	motor[leftMotor] = 80;
	motor[rightMotor] = 20;
	wait1Msec(300);
	motor[leftMotor] = 40;
	motor[rightMotor] = 40;
	wait1Msec(2000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
void moveHardRight(){
	motor[leftMotor] = 40;
	motor[rightMotor] = -40;
	wait1Msec(700);
	motor[leftMotor] = 40;
	motor[rightMotor] = 40;
	wait1Msec(2000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}


int ServoMove(int servoPosition){

  //writeDebugStreamLine("Servo Position = %d",servoPosition);
  int light = SensorValue(light_sensor); //gets light sensor value
  //writeDebugStreamLine("POT = %d",SensorValue(POT));
  motor[Servo] = servoPosition; //moves servo to current position
  wait1Msec(200);
  return light;
}

task main()
{
	while(true){
		//SCANNING STATE
		int max_position = -127; //sets default max position to first position
		int max_light = 800; //sets default max light to 800 (lowest light value)
		int max_POT = 3000;
		bool b = true;
		if(b){
			for(int i = -127; i<127 ; i +=10){ //checks all values in servo range incrementing by 10
			ServoMove(i);
			if (ServoMove(i) < max_light){ //if current light value is greater than the max, max light value becomes current light value and
				                             //max position value is changed to current position
				max_light = ServoMove(i);
				max_position = i;
				max_POT = SensorValue(POT);
			}
				}
			}
			motor[Servo]=max_position; //moves servo to position with the most light
			//ServoMove(max_position);
			wait1Msec(2000);
			writeDebugStreamLine("%d",max_position);
			int angle = (max_POT - 3415)/-15.6;
			writeDebugStreamLine("%d, <- ANGLE",angle);
			//DECISION
			if (max_light > 700){
				//int time = (rand() % (2000 + 1 - 500)+500);
				int time = 1000;
				writeDebugStream("%d, TIME1", time);
				motor[leftMotor]= -50; //Reverses the direction that Squarebot is going so it backs up.
				motor[rightMotor]= 0;
				wait1Msec(time);//Makes Squarebot stop for a random amount of time.
				motor[leftMotor]= 0;
				motor[rightMotor]= 0;
				wait1Msec(500);


				int time2 = 2000;
				motor[leftMotor]= 50; //Reverses the direction that Squarebot is going so it backs up.
				motor[rightMotor]= 38;
				wait1Msec(time2);
				motor[leftMotor]= 0;
				motor[rightMotor]= 0;

			}else if((80 < angle) &&(angle <= 100)){//Threshold for different turn radius
				moveStraight();
			} else if ((100 < angle) &&(angle <= 135)) {
				moveSoftLeft();
			}else if (135 < angle) {
				moveHardLeft();
			}else if ((45 < angle) &&(angle <= 80)){
				moveSoftRight();
			}else if(angle <= 45) {
				moveHardRight();
			}else {
				writeDebugStreamLine("SOL");
			}
	}
}
